# Generated by Django 5.0 on 2024-07-02 11:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='bookstore/%Y/%m/%d')),
                ('title', models.CharField(max_length=2000)),
                ('author', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(default='No description available', max_length=99999999)),
                ('tag', models.CharField(max_length=100)),
                ('link', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(default='No description available', max_length=1000)),
                ('image', models.ImageField(upload_to='blogPostImages/%Y/%m/%d')),
                ('tag', models.CharField(max_length=10)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('time', models.TimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
