# Generated by Django 5.0 on 2024-07-02 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog01', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='description',
            new_name='post',
        ),
    ]
