# Generated by Django 5.0 on 2024-07-02 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog01', '0002_rename_description_blogpost_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='post',
            field=models.CharField(default='No description available', max_length=10000),
        ),
    ]
