# Generated by Django 5.0 on 2023-12-06 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog01', '0002_blogpost_description_alter_blogpost_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='description',
            field=models.CharField(default='No description available', max_length=99999999),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='tag',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=2000),
        ),
    ]
