# Generated by Django 5.0 on 2024-07-02 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog01', '0003_alter_blogpost_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='time',
        ),
    ]
