# Generated by Django 5.0 on 2023-12-11 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog01', '0003_alter_blogpost_description_alter_blogpost_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(upload_to='post_images/%Y/%m/%d'),
        ),
    ]
