# Generated by Django 5.0 on 2023-12-11 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog01', '0004_alter_blogpost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(upload_to='blogpost/%Y/%m/%d'),
        ),
    ]
