# Generated by Django 5.0 on 2024-07-04 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog01', '0004_remove_blogpost_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookStore',
        ),
    ]
