# Generated by Django 5.0 on 2023-12-14 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog01', '0006_blogpost_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blogpost/%Y/%m/%d')),
                ('title', models.CharField(max_length=2000)),
                ('author', models.CharField(blank=True, max_length=100)),
                ('tag', models.CharField(max_length=100)),
            ],
        ),
    ]
