# Generated by Django 5.0 on 2023-12-14 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog01', '0007_bookstore'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookstore',
            name='description',
            field=models.CharField(default='No description available', max_length=99999999),
        ),
        migrations.AddField(
            model_name='bookstore',
            name='link',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
