# Generated by Django 5.0 on 2023-12-14 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog01', '0008_bookstore_description_bookstore_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookstore',
            name='image',
            field=models.ImageField(upload_to='bookstore/%Y/%m/%d'),
        ),
    ]
